<table class="table table-sm" style="text-align: center;">
    <thead>
        <tr>
            <th>DIAG_UTAMA</th>
            <th>NAMA_DIAG</th>
            <th>NO_RM</th>
            <th>TGL_MASUK</th>
            <th>TGL_KELUAR</th>
            <th>ket</th>
            <th>KELAS</th>
            <th>KODEICD</th>
            <th>JKL</th>
            <th>JKP</th>
            <th>KOMPLIKASI</th>
            <th>DIAGNOSA_SEK</th>
            <th>OPERASI</th>
            <th>MATIKR48</th>
            <th>alamat</th>
            <th>U0_28HR</th>
            <th>ULB65TH</th>
            <th>U1_4TH</th>
            <th>U5_14TH</th>
            <th>U15_24TH</th>
            <th>U25_44TH</th>
            <th>U45_59TH</th>
            <th>U60_64TH</th>
            <th>ULB65TH</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($lpri as $item)
        <tr>
            <td>{{$item->DIAG_UTAMA}}</td>
            <td>{{$item->NAMA_DIAG}}</td>
            <td>{{$item->NO_RM}}</td>
            <td>{{$item->TGL_MASUK}}</td>
            <td>{{$item->TGL_KELUAR}}</td>
            <td>{{$item->ket}}</td>
            <td>{{$item->KELAS}}</td>
            <td>{{$item->KODEICD}}</td>
            <td>{{$item->JKL}}</td>
            <td>{{$item->JKP}}</td>
            <td>{{$item->KOMPLIKASI}}</td>
            <td>{{$item->DIAGNOSA_SEK}}</td>
            <td>{{$item->OPERASI}}</td>
            <td>{{$item->MATIKR48}}</td>
            <td>{{$item->alamat}}</td>
            <td>{{$item->U0_28HR}}</td>
            <td>{{$item->ULB65TH}}</td>
            <td>{{$item->U1_4TH}}</td>
            <td>{{$item->U5_14TH}}</td>
            <td>{{$item->U15_24TH}}</td>
            <td>{{$item->U25_44TH}}</td>
            <td>{{$item->U45_59TH}}</td>
            <td>{{$item->U60_64TH}}</td>
            <td>{{$item->ULB65TH}}</td>
        </tr>
        @endforeach

    </tbody>
</table>
